### ISSUE TITLE
Add inbound file path property to Metadata

### ISSUE THREAD

**Issue by amrabuzaljko** [ConnXio/ConnXio#17]
### Problem
When `Handle file as binary` option is enabled, split/batch and transformations are not supported, meaning no user defined property can be set nor used in Outbound adapters. Adding the Inbound file path to Metadata can - in some use cases - provide useful variable replacements for such purposes. 

### Solution
Add Inbound file path property to `Metadata` Transformation Context
![image](https://user-images.githubusercontent.com/55737226/206766939-a36be8e4-9d31-4b57-a8fb-eb262b6be764.png)

**Comment by lmrisdal** [comment]
[This is now in production](https://docs.connxio.no/changelog/1.9.2)
