### ISSUE TITLE
REST Outbound adapter won't send specified header values

### ISSUE THREAD

**Issue by amrabuzaljko** [ConnXio/ConnXio#18]
**Describe the bug**
When `Handle file as binary` option is enabled, the Outbound REST adapter does not send specified Header values.

**To Reproduce**
1. Enable `Handle file as binary` option 
![image](https://user-images.githubusercontent.com/55737226/206769781-6933fb21-5e5b-49bf-8d51-16acaaafbb42.png)

2. Add REST Outbound connection
![image](https://user-images.githubusercontent.com/55737226/206769836-9031bd0c-4369-4fde-bc1e-217e3d2799ca.png)

3. Specify header values 
![image](https://user-images.githubusercontent.com/55737226/206769990-8d367289-a263-48da-882a-475a59d4af79.png)

5. Trigger the integration
6. Observe that the above header values are not set in the outbound request
![image](https://user-images.githubusercontent.com/55737226/206770130-154b19ed-524f-4d32-8012-b94aa1ff33e6.png)

**Expected behavior**
Specified headers should appear

**Comment by lmrisdal** [comment]
This is now fixed
