### ISSUE TITLE
Add option to start logging with new interchange when receiving messages from blob storage

### ISSUE THREAD

**Issue by kleivers** [connxio/connxio#21]
### Problem
One integration sends a file to blob storage. A new integration receives the same blob via blob storage adapter. The interchange Id is fetched from metadata and logging continues on same interchange in Archeo. There should be a flag/option to start a new separate interchange on this new interchange.

### Solution
Add a flag/option in blob storage config on inbound that creates a new interchange in Archeo if selected.

**Comment by JonasMoltzau** [comment]
This is doable, and not a lot of work. We will review this after Christmas and put it in the backlog.

**Comment by enis-j** [comment]
Any updates on this issue?

**Comment by JonasMoltzau** [comment]
No updates yet I'm afraid. I can push for this to be prioritized, else it will probably be fixed with the coming of V2.

**Comment by JonasMoltzau** [comment]
Descussed this with the team and we aim to realese this to production with other new updates for v1. I'll come back with a data. Shoudl be within the next 2 weeks.
