### ISSUE TITLE
Name inbound connections

### ISSUE THREAD

**Issue by afagerborg** [ConnXio/ConnXio#23]
### Problem
When viewing/editing an integration it would increase readability if you also could give inbound connections a name, even if you are only allowed to have one connection, and assuming different people will be viewing/editing the integration.
Like for apis, would be useful to describe the party sending data

### Solution
Add name to inbound connecions

### Additional context
Only nice to have feature

**Comment by JonasMoltzau** [comment]
Love the input. This will unfortunatly not be fixed in the foreeable future.
