### ISSUE TITLE
Larger than expected delay on execution when using Process Lock on inbound SFTP

### ISSUE THREAD

**Issue by enis-j** [ConnXio/ConnXio#27]
**Describe the bug**
When using inbound SFTP with Process Lock enabled, it seems like the polling interval is delayed quite a bit, sometimes over an hour even though there are 1K+ files on the SFTP-server. 

**To Reproduce**
1. Create integration with inbound SFTP
2. Enable process lock
3. Make sure process runs for minimum 5 mins (tested with average around 350 seconds)
4. Wait for the next polling interval.

**Expected behavior**
After the process is finished, I would expect it to run again after 60 seconds, or within the polling interval defined in the integration config. 

**Screenshots**
- Integration config: 
    ![image](https://user-images.githubusercontent.com/32385783/215983916-d719ecbc-e81e-4e87-b418-40321b4c8d58.png)

- Highlight of issue: 
    ![image](https://user-images.githubusercontent.com/32385783/215983257-f7da7f72-ea91-48f1-875c-9bbef54bf72f.png)

**Comment by JonasMoltzau** [comment]
This is probably related to the time it takes to list all the files. We saw a similar pattern of behaviour when we tested the old lock system with Øyvind, before we moved the locking mechanism to the new pattern. I can take a look at it but i would guess that this requires a totally new read pattern or a new SDk for the (S)FTP adapter.

**Comment by JonasMoltzau** [comment]
Looked at it. Put in a fix that prevents deadlock but it wont really fix the problem since it could cause the process to run in paralell instead, but it's probably better than the alternative.
