### ISSUE TITLE
502 Gateway error when upserting `new` integration via Managment API

### ISSUE THREAD

**Issue by enis-j** [ConnXio/ConnXio#28]
**Describe the bug**
POST  /api/management/integration returns 502 when i'm trying to upsert a new integration.  

**To Reproduce**
1. Send POST call to /api/management/integration (make sure the integration doesn't exist)
2. Observe 502 response with the following errorMessage: "Could not contact database for existing integration validation. Please try again later, as this error should be transient."

**Screenshots**
![image](https://user-images.githubusercontent.com/32385783/216982116-5d4f12e7-dc7c-4f88-87a1-4781e349d6fd.png)

**Additional context**
- First observed this issue on Thursday 02.02.23.
- Contact me for request body as it contains some sensitive information.

**Comment by JonasMoltzau** [comment]
@shskjetne is on the case. Looks like it's a bug when checking if the integration exists.

**Comment by JonasMoltzau** [comment]
Fixed. Should work now.
