### ISSUE TITLE
Keep servicebus system and custom properties when reading, transforming, and sending servicebus messages

### ISSUE THREAD

**Issue by Halfmanification** [ConnXio/ConnXio#29]
### Problem
ConnXio today discards all system and custom properties of a servicebus message and essentially only considers the body content of the sb message. Often these properties are used to send metadata about a message that are relevant for consumers, loggers, or other parts of a system that is outside ConnXio, so when these are not kept on ingress and are available through a ConnXio integration, context and information is lost.

### Solution
Instead of TransformationContext.Content just containing the body of a servicebus message, let it contain the entire servicebus message, body + metadata and let the developer control these themselves.

### Additional context
The servicebus message properties discussed are these kinds of properties:
![image](https://user-images.githubusercontent.com/27742958/218681835-b9da914d-bc71-44af-9602-9dd0eaf2926c.png)

**Comment by Halfmanification** [comment]
Don't hesitate to contact me directly if any clarification about our use case is needed.

**Comment by shskjetne** [comment]
We'll probably solve this by adding an option to keep the "whole" sbMessage on inbound and adding a class to the transformation NuGet that can be used to deserialize the messing during a codeComponent-transformation. I'll be back with more information soon.

**Comment by JonasMoltzau** [comment]
DOne
