### ISSUE TITLE
Allow to save a new integration in any state as long as it has a name, but put the restrictions on when it can be enabled

### ISSUE THREAD

**Issue by Halfmanification** [connxio/connxio#30]
### Problem
To successfully create a new integration, I need to gather all the necessary information beforehand. If I forget to include a security configuration, for instance, I cannot save the integration and must start over from the beginning after adding the missing or finding the missing data.

### Solution
Rather than limiting the ability to save a new integration, I recommend allowing the user to create and save an integration with minimal configuration. Instead, the restrictions should be applied to the "Enable Integration" button. This would allow me to work on a new integration gradually, save my progress, and resume later on with ease, resulting in a more seamless integration setup experience.

**Comment by lmrisdal** [comment]
This is implemented in v2.
