### ISSUE TITLE
Clone integration - disable by default or make user option

### ISSUE THREAD

**Issue by kristintonn** [connxio/connxio#35]
### Problem
I have a set of integrations in a test environment. I want to prepare for production by cloning the integrations and updating the configs and urls etc, but do not want them to run yet. If the integrations are enabled in the test environment, they are also enabled in the production environment. Now I have to disable the test integration, clone it and enable again.

### Solution
Either let integration clones be disabled by default or give the user the option to set enabled/disabled in the clone window.
I would also like to have a spinner after clicking "Clone". I have ended up with duplicate clones because I was unsure of whether the process had started and clicked again.

**Comment by lmrisdal** [comment]
This is now in production.
