### ISSUE TITLE
export/import json

### ISSUE THREAD

**Issue by afagerborg** [connxio/connxio#37]
When cloning between environments, it is A LOT of settings for some integrations. Easy to forget something.
I know about env variables, bit not possible for everything. 

Could be available as a "super-user option":
- Export a setting from an environment, to json file in your editor of choice
- Import the file as a new integration to your current environment 
- Name will get name ending IMPORTED or something
- Should probably validate that everything is valid first, like that security configs exist. 

Obviously a risk of failure here, so will probably never get this, but would save time.

**Comment by shskjetne** [comment]
There are already two ways to clone an integration between environments:

1. You can clone an integration by using the "Clone" functionality in the portal. To do this, follow these steps:
   - Navigate to the integration overview.
   - Locate the integration you want to clone and click on the menu button, which is located on the far right of the integration 
   line.
   - Select the "Clone" option.
   
2. Another option is to use the Management API. You can find detailed information about using the Management API for cloning integrations in the documentation at this link: https://docs.connxio.no/Management/management-api.

Is this what you are looking for, or do you need any other features?

**Comment by afagerborg** [comment]
Not aware of option 2, and did not get how this works and what it does.

Maybe a quick talk when u have time

Vennlig hilsen/Best regards
​
Arvid Fagerborg
Lead Developer, Evidi
​​
+47 92032006 | ***@***.***
​evidi.com

________________________________

**Comment by lmrisdal** [comment]
Closing because of lack of update. Reopen if needed.
