### ISSUE TITLE
Add support for delta date on data collection

### ISSUE THREAD

**Issue by kleivers** [connxio/connxio#44]
### Problem
Delta date is only available on inbound, and not stored in any metadata that are reachable from the transformation step. Currently, using {date.UseDateTimeDelta(1980-01-01T08:00:00.00).SetCstZone(Central Europe Standard Time) | date: yyyy-MM-dd HH:mm:ss.fff } returns DateTime.Now().

### Solution
Add support for using delta datetime value on data collection step. Either ability to turn on on each subflow, or just available via variable replacement.

**Comment by JonasMoltzau** [comment]
Done
