### ISSUE TITLE
User defined property not properly set in logging override

### ISSUE THREAD

**Issue by amrabuzaljko** [connxio/connxio#45]
**Describe the bug**
When referring to a custom user defined property in the logging override section in CX, the variable does not seem to be replaced properly.

**To Reproduce**

Using a split component, add a user defined property to the metadata context:

In the `Outbound format and logging override` section in ConnXio, set the user defined properties mentioned above

Observe that the user defined properties are set when the integration has completed the run

**Expected behavior**
Would expect both the `Transaction Tag` and the `Sender` to be populated with the above values for `SkanolOrderId` and `StationId`, respectively.

Instead, only the `Transaction Tag` is set, while the `Sender` fails to be set in Archeo.

**Screenshots**

**Comment by JonasMoltzau** [comment]
Implemented. Coming to production next week.

**Comment by JonasMoltzau** [comment]
Deployed to production
