### ISSUE TITLE
Failures - export message content

### ISSUE THREAD

**Issue by afagerborg** [connxio/connxio#48]
### Problem
Sometimes we want to just delete the failure, but would like to have a copy of the message content.
Solution now is to view message content, select everything and then copy.
Problem with large files and some formats

### Solution
Have a button beside "view message content" ; "Download message content".
By clicking, the message is saved to file with the original filename

**Comment by lmrisdal** [comment]
This is already implmeneted in v2 :-)

**Comment by afagerborg** [comment]
V2 will make connexio great(er)!
