### ISSUE TITLE
Unsupported SSL protocol for www.communicate.no

### ISSUE THREAD

**Issue by fredrikhr** [connxio/connxio#53]
**Describe the bug**
The site https://www.communicate.no/en/connxio is not reachable with a modern browser.
> Unsupported protocol
> The client and server don't support a common SSL protocol version or cipher suite.
> ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**To Reproduce**
1. Go to https://docs.connxio.no/
2. Click on the link [About ConnXio](https://www.communicate.no/en/connxio) in the top navigation bar
3. See error returned by the web browser
    > The connection for this site is not secure
    > www.communicate.no uses an unsupported protocol.
    > ERR_SSL_VERSION_OR_CIPHER_MISMATCH
    > Unsupported protocol
    > The client and server don't support a common SSL protocol version or cipher suite.

**Expected behavior**
I expected to be redirected to web site that explains what ConnXio is.

**Additional context**
Using Microsoft Edge
Version 117.0.2048.60 (Official build) (64-bit)
Using Windows 11 Pro, version 22H2, OS build 22621.2361

**Comment by JonasMoltzau** [comment]
This is because of the move to Evidi. This is fixed in v2.

**Comment by JonasMoltzau** [comment]
Also removed the link in old doc
