### ISSUE TITLE
Suggestion: Add Search Fields to ConnXio

### ISSUE THREAD

**Issue by DuongNguyen1610** [connxio/connxio#64]
### Problem
There is currently no functionality to search for code components or security configurations once they have been added. This makes it time-consuming because I need to scroll through the entire dropdown list every time to find the correct one to use. Also it is challenging to distinguish between code components and security configurations for each environment since they are all listed in the same dropdown

### Solution
Add search fields into ConnXio, maybe like the example in the picture below

![image](https://github.com/connxio/connxio/assets/147493854/a298f824-1d71-40ef-b98f-18c8f50f907d)

**Comment by JonasMoltzau** [comment]
Good suggestion. I've added it to the backlog.

**Comment by lmrisdal** [comment]
Implemented in v2
