### ISSUE TITLE
[BUG]: Updating environment variables not updating for subscriptions

### ISSUE THREAD

**Issue by daniel-soli** [connxio/connxio#69]
**Describe the bug**
When trying to update an environment variable, which has previously only had default value, with different values per subscripion it does not update. It is sent in the request, but response does not indicate that the list has been updated. 
Refreshing, relogging in etc does not afect the result. 

**To Reproduce**
1. Go to `Environment Variables`
2. Click on Add
3. Only add default value
4. Save
5. Try to add new values per subscription

**Expected behavior**
When updating values per subscription, expected to be updated.

**Screenshots**
![image](https://github.com/user-attachments/assets/b5024c95-1434-441b-b6c3-d0669d232593)
![image](https://github.com/user-attachments/assets/044eb830-e2b4-48fc-ac4a-182ae0b31a9d)
![image](https://github.com/user-attachments/assets/0ce3f65d-ad01-4801-bad4-21cf3b850311)

**Comment by lmrisdal** [comment]
Does this happen consistently for you? Having trouble recreating it.

**Comment by daniel-soli** [comment]
> Does this happen consistently for you? Having trouble recreating it.

Yes, it happened all the time for all variables. 
But it seems to have been fixed now for some reason :) 

So you can close this.
