### ISSUE TITLE
[BUG] Deleting failed integrations not working

### ISSUE THREAD

**Issue by daniel-soli** [connxio/connxio#70]
**Describe the bug**
When trying to delete failed integration messages it just keeps "loading". If multiple are selected (100s) it may be able to delete some, but not all. 
It worked well a week or 2 ago, but now it only loads and just a handful is actually deleted. 
Also, the numbers shown in the details are wrong.

![image](https://github.com/user-attachments/assets/d0ed74e5-e76f-40a3-a52b-0506bad7e3df)

**To Reproduce**
1. Go to Failures
2. Select all messages on page or All in general.
3. Press delete
4. See nothing really happening

**Expected behavior**
All messages to be deleted

**Comment by lmrisdal** [comment]
@Jonaseli identified a bug here. We'll let you know when we have a fix ready ✌️

**Comment by lmrisdal** [comment]
@daniel-soli This should be fixed now. Let us know if you're still getting issues!

**Comment by daniel-soli** [comment]
@lmrisdal Works like a charm :) great work!
